<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<!-- CRUCIAL: Forzar 32 bits para la DLL -->
		<PlatformTarget>x86</PlatformTarget>
		<RuntimeIdentifier>win-x86</RuntimeIdentifier>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
		<PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="10.0.10" />
		<PackageReference Include="RawPrint.NetStd" Version="1.0.0" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
		<PackageReference Include="System.IO.Ports" Version="8.0.0" />
		<PackageReference Include="System.Management" Version="7.0.2" />
	</ItemGroup>

	<!-- Configuración correcta para copiar la DLL -->
	<ItemGroup>
		<Content Include="DLLs\tfhkaif.dll">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		</Content>
	</ItemGroup>
	<ItemGroup>
	  <Folder Include="Utilities\" />
	</ItemGroup>

</Project>